import Head from "next/head";
import styles from "../styles/Home.module.css";
import Form from "@rjsf/core";
// import Form from "@rjsf/bootstrap-4";
import "bootstrap/dist/css/bootstrap.min.css";
import schema from "./forms/translations.json";
import uiSchema from "./forms/uiSchema/translations.json";
import {
  materialRenderers,
  materialCells,
} from "@jsonforms/material-renderers";
import { JsonForms } from "@jsonforms/react";
import { useState } from "react";
import initialData from "./forms/data/en-GB.json";

const log = (type) => console.log.bind(console, type);

export default function Home() {
  const [data, setData] = useState(initialData);
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <div className="container">
          <Form
            schema={schema}
            uiSchema={uiSchema}
            onChange={log("changed")}
            onSubmit={log("submitted")}
            onError={log("errors")}
          />

          {/* <JsonForms
            schema={schema}
            uischema={uiSchema}
            data={data}
            renderers={materialRenderers}
            cells={materialCells}
            onChange={({ data, _errors }) => setData(data)}
          /> */}
        </div>
      </main>

      <footer className={styles.footer}></footer>
    </div>
  );
}
